[project]
name = "vbt-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[project.scripts]
serve = "vbt_flow:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
